package com.halilibrahim.hrms.core.utilities.verifications.mernis;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.12.12.0
//
// Created by Quasar Development 
//
//----------------------------------------------------



public interface LIWIServiceEvents
{
    void Starting();
    void Completed(LIWOperationResult result);
}
